#  Travis uses virtual envs for python and here want to use conda python
language: c

branches:
  only:
  - master
  - variable-definitions

env:
  # Build and test package on all supported python versions
  # NOTE: Miniconda version could be widely expanded
  - PYTHON_BUILD_TARGET=3.8 MINICONDA_VERSION=4.7.12
  - PYTHON_BUILD_TARGET=3.7 MINICONDA_VERSION=4.7.12
  - PYTHON_BUILD_TARGET=3.6 MINICONDA_VERSION=4.7.12
  # To make sure it's still working with conda 4.6
  - PYTHON_BUILD_TARGET=3.8 MINICONDA_VERSION=4.6.14
  - PYTHON_BUILD_TARGET=3.7 MINICONDA_VERSION=4.6.14
  - PYTHON_BUILD_TARGET=3.6 MINICONDA_VERSION=4.6.14

os:
  - linux
  - osx


install:
  - sudo apt update
  # Install the appropriate miniconda depending on the os and miniconda version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh

  # set configs
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge --set channel_priority strict

  # log info for debugging
  - conda info -a

  # create env
  - conda create -q -n test-environment python=$PYTHON_BUILD_TARGET --file dev-requirements.txt

  - conda activate test-environment

script:
  - pytest
