#  Travis uses virtual envs for python and here want to use conda python
language: c

branches:
  only:
  - master
  - variable-definitions

env:
  # Build and test package on all supported python versions
  # NOTE: Miniconda version could be widely expanded
  - BUILD_TARGET=3.8 MINICONDA_VERSION=4.7.12
  - BUILD_TARGET=3.7 MINICONDA_VERSION=4.7.12
  - BUILD_TARGET=3.6 MINICONDA_VERSION=4.7.12
  # To make sure it's still working with conda 4.6
  - BUILD_TARGET=3.8 MINICONDA_VERSION=4.6.14
  - BUILD_TARGET=3.7 MINICONDA_VERSION=4.6.14
  - BUILD_TARGET=3.6 MINICONDA_VERSION=4.6.14

os:
  - linux
  - osx

before_install:
  # Install the appropriate miniconda depending on the os and miniconda version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt

install:
  - conda install -y conda-build

  # add conda forge for epics-base etc.
  - conda config --add channels conda-forge

  # Build the conda recipe for this package
  - conda build -q conda-recipe --python=$TRAVIS_PYTHON_VERSION --output-folder bld-dir

  # Add the built package as a channel with highest priority
  # this can eventually be used to deploy to conda-forge
  - conda config --add channels "file://`pwd`/bld-dir"

  # Create and activate a python environment
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION --file dev-requirements.txt --yes
  - source activate test-environment

script:
  - pytest
