name: Test on GPU

on:
  push:
  workflow_dispatch:

jobs:
  check_gpu:
    runs-on: linux-nvidia-gpu
    steps:
      - name: Check for NVIDIA GPU presence
        run: nvidia-smi
        continue-on-error: true
