name: Test on GPU

on:
  workflow_dispatch:

jobs:
  check_gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Check for NVIDIA GPU presence
        run: nvidia-smi
        continue-on-error: true
